import React, { useState, useCallback } from 'react';
import { generateImage } from '../services/geminiService';
import { ASPECT_RATIOS } from '../constants';

const ImageGenerator: React.FC = () => {
  const [prompt, setPrompt] = useState<string>('');
  const [aspectRatio, setAspectRatio] = useState<string>('1:1');
  const [generatedImageUrl, setGeneratedImageUrl] = useState<string | null>(null);
  const [loading, setLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);

  const handleGenerateImage = useCallback(async () => {
    if (!prompt.trim()) {
      setError('Please enter a prompt for the image.');
      return;
    }

    setLoading(true);
    setGeneratedImageUrl(null);
    setError(null);

    try {
      const imageUrls = await generateImage(prompt, aspectRatio);
      if (imageUrls && imageUrls.length > 0) {
        setGeneratedImageUrl(imageUrls[0]);
      } else {
        setError('No image was generated. Please try a different prompt.');
      }
    } catch (err: any) {
      console.error(err);
      if (err.message && err.message.includes("API key not valid")) {
        setError("Invalid API Key. Please check your environment configuration.");
      } else {
        setError(`Failed to generate image: ${err.message || 'Unknown error'}`);
      }
    } finally {
      setLoading(false);
    }
  }, [prompt, aspectRatio]);

  return (
    <div className="bg-white p-6 rounded-lg shadow-md mb-8">
      <h2 className="text-2xl font-bold text-gray-900 mb-4">Gemini Image Generator</h2>

      <div className="mb-4">
        <label htmlFor="image-prompt" className="block text-sm font-medium text-gray-700 mb-2">
          Image Prompt:
        </label>
        <textarea
          id="image-prompt"
          className="w-full p-3 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500 transition-all duration-200 ease-in-out"
          rows={4}
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          placeholder="Describe the image you want to generate (e.g., 'A robot holding a red skateboard in a futuristic city')."
          disabled={loading}
        ></textarea>
      </div>

      <div className="mb-6 flex flex-col sm:flex-row items-start sm:items-center space-y-3 sm:space-y-0 sm:space-x-4">
        <label htmlFor="aspect-ratio" className="block text-sm font-medium text-gray-700">
          Aspect Ratio:
        </label>
        <select
          id="aspect-ratio"
          value={aspectRatio}
          onChange={(e) => setAspectRatio(e.target.value)}
          className="block w-full sm:w-auto px-3 py-2 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm transition-all duration-200 ease-in-out"
          disabled={loading}
        >
          {ASPECT_RATIOS.map((ratio) => (
            <option key={ratio} value={ratio}>
              {ratio}
            </option>
          ))}
        </select>
      </div>

      <button
        onClick={handleGenerateImage}
        className="w-full px-6 py-3 bg-indigo-600 text-white rounded-lg shadow-lg hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-opacity-50 transition-all duration-200 ease-in-out disabled:opacity-50 disabled:cursor-not-allowed"
        disabled={loading}
      >
        {loading ? (
          <span className="flex items-center justify-center">
            <svg className="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
            </svg>
            Generating Image...
          </span>
        ) : 'Generate Image'}
      </button>

      {error && (
        <div className="mt-4 p-3 bg-red-100 border border-red-400 text-red-700 rounded-md">
          {error}
        </div>
      )}

      {generatedImageUrl && (
        <div className="mt-6 p-4 bg-gray-50 rounded-md border border-gray-200 text-center">
          <h3 className="text-lg font-semibold text-gray-800 mb-2">Generated Image:</h3>
          <img
            src={generatedImageUrl}
            alt="Generated by Gemini"
            className="max-w-full h-auto mx-auto rounded-lg shadow-md border border-gray-300"
          />
        </div>
      )}
    </div>
  );
};

export default ImageGenerator;